spring:
  application:
    name: auth-service

jwt:
  secret: "QmCTh1o5dV6TQzL9vG7g2c3Lx8zF4pN0sUwE1rYtZjXoKbHd5S2aQ9fM3nVwR8tY"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
