spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: "QmCTh1o5dV6TQzL9vG7g2c3Lx8zF4pN0sUwE1rYtZjXoKbHd5S2aQ9fM3nVwR8tY"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
