spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<remaining>.*), /${remaining}
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    instance:
      prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: "QmCTh1o5dV6TQzL9vG7g2c3Lx8zF4pN0sUwE1rYtZjXoKbHd5S2aQ9fM3nVwR8tY"
