spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://db:5432/hoteldb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
